-- load doctors and patients tables from csv files
--Question 2. Use the `psql` `\copy` command to load the doctors and patients tables from the files `data/doctors.csv` and `data/patients.csv` respectively.
  --+ Save your code in `scripts/load_doctors_and_patients.psql`.

\copy doctors(surname,given_name,gender,dob,specialty) FROM 'data/doctors.csv' WITH (HEADER true, FORMAT csv)

\copy patients(surname,given_name,gender,dob,insurance) FROM 'data/patients.csv' WITH (HEADER true, FORMAT csv)
